### ISSUE TITLE
KeyError: 'robomimic_bc_cfg_entry_point' while running Imitation Learning training script

### ISSUE THREAD

**Issue by OwlllOvO** [orbit-surgical/orbit-surgical#12]
#### Description

I'm encountering a `KeyError` while executing the Imitation Learning training script for the task `Isaac-Lift-Needle-PSM-IK-Rel-v0`

#### Command Executed

This command is the one provided in the README under Imitation Learning, 3. Train a BC agent for `Isaac-Lift-Needle-PSM-IK-Rel-v0` with Robomimic:

```bash
${IsaacLab_PATH}/isaaclab.sh -p source/standalone/workflows/robomimic/train.py --task Isaac-Lift-Needle-PSM-IK-Rel-v0 --algo bc --dataset logs/robomimic/Isaac-Lift-Needle-PSM-IK-Rel-v0/hdf_dataset.hdf5
```

#### Error Log

```
(orbitsurgical) owlllovo@owlllovo-MS-7C04:~/Repos/orbit-surgical$ ${IsaacLab_PATH}/isaaclab.sh -p source/standalone/workflows/robomimic/train.py --task Isaac-Lift-Needle-PSM-IK-Rel-v0 --algo bc --dataset logs/robomimic/Isaac-Lift-Needle-PSM-IK-Rel-v0/hdf_dataset.hdf5
[INFO] Using python from: /home/owlllovo/miniconda3/envs/orbitsurgical/bin/python                                                                                                                      
[INFO][AppLauncher]: Loading experience file: /home/owlllovo/Repos/IsaacLab/source/apps/isaaclab.python.headless.kit
Loading user config located at: '/home/owlllovo/.local/share/ov/pkg/isaac-sim-4.2.0/kit/data/Kit/Isaac-Sim/4.2/user.config.json'
[Info] [carb] Logging to file: /home/owlllovo/.local/share/ov/pkg/isaac-sim-4.2.0/kit/logs/Kit/Isaac-Sim/4.2/kit_20241114_205419.log
2024-11-15 04:54:19 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.

|---------------------------------------------------------------------------------------------|
| Driver Version: 535.183.01    | Graphics API: Vulkan
|=============================================================================================|
| GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |     |            | Device-ID | UUID       |
|     |                                  |        |     |            | Bus-ID    |            |
|---------------------------------------------------------------------------------------------|
| 0   | NVIDIA GeForce RTX 2070          | Yes: 0 |     | 8438    MB | 10de      | 0          |
|     |                                  |        |     |            | 1f07      | d1f3dd4b.. |
|     |                                  |        |     |            | 1         |            |
|=============================================================================================|
| OS: 20.04.6 LTS (Focal Fossa) ubuntu, Version: 20.04.6, Kernel: 5.15.0-125-generic
| XServer Vendor: The X.Org Foundation, XServer Version: 12013000 (1.20.13.0)
| Processor: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz | Cores: 6 | Logical: 6
|---------------------------------------------------------------------------------------------|
| Total Memory (MB): 15922 | Free Memory: 12415
| Total Page/Swap (MB): 2047 | Free Page/Swap: 2047
|---------------------------------------------------------------------------------------------|
Loading configuration for task: Isaac-Lift-Needle-PSM-IK-Rel-v0
Traceback (most recent call last):
  File "/home/owlllovo/Repos/orbit-surgical/source/standalone/workflows/robomimic/train.py", line 418, in <module>
    main(args)
  File "/home/owlllovo/Repos/orbit-surgical/source/standalone/workflows/robomimic/train.py", line 353, in main
    cfg_entry_point_file = gym.spec(args.task).kwargs.pop(cfg_entry_point_key)
KeyError: 'robomimic_bc_cfg_entry_point'
2024-11-15 04:54:23 [4,365ms] [Warning] [carb] Recursive unloadAllPlugins() detected!

```

#### Environment

- **Python Version**: 3.10.15
- **Operating System**: Ubuntu 20.04.6 LTS
- **GPU**: NVIDIA GeForce RTX 2070
- **Driver Version**: 535.183.01
- **Isaac Sim Version**: 4.2.0

#### Steps to Reproduce

1. Execute the Imitation Learning training command.
2. Observe the error output.

#### Expected Behavior

The training script should execute without raising a `KeyError` and proceed with the training.

**Comment by KDeng98** [comment]
Hi there,
I am also facing this problem. Did you manage to solve it? Would you mind sharing any thoughts about how to solve it? Thanks!

**Comment by OwlllOvO** [comment]
> Hi there, I am also facing this problem. Did you manage to solve it? Would you mind sharing any thoughts about how to solve it? Thanks!

Unfortunately I still haven't figured out the issue, and don’t have any new updates to share. Plus, I've stopped working on the project, sorry about that!

**Comment by masoudmoghani** [comment]
Hi, Thanks for your interest in the project. The robomimic cfg file is currently missing, the repo will be updated within the next week with more imitation learning algos.

Best,
Masoud

**Comment by fefei69** [comment]
Hi, Using `robomimic/bc.json` as the entry point will get away the KeyError, Thank you. Like this in [here](https://github.com/orbit-surgical/orbit-surgical/blob/main/source/extensions/orbit.surgical.tasks/orbit/surgical/tasks/surgical/lift/config/needle/__init__.py):

```python
gym.register(
    id="Isaac-Lift-Needle-PSM-IK-Rel-v0",
    entry_point="omni.isaac.lab.envs:ManagerBasedRLEnv",
    kwargs={
        "env_cfg_entry_point": ik_rel_env_cfg.NeedleLiftEnvCfg,
        "rsl_rl_cfg_entry_point": agents.rsl_rl_cfg.LiftNeedlePPORunnerCfg,
        "robomimic_bc_cfg_entry_point": os.path.join(agents.__path__[0], "robomimic/bc.json")
    },
    disable_env_checker=True,
)
