### ISSUE TITLE
Error when running Teleoperation

### ISSUE THREAD

**Issue by relifeto18** [orbit-surgical/orbit-surgical#8]
Hi,

An error occurred when I tried to run the Teleoperation task.
`${IsaacLab_PATH}/isaaclab.sh -p source/standalone/environments/teleoperation/teleop_se3_agent.py --task Isaac-Lift-Needle-PSM-IK-Rel-v0 --num_envs 1 --teleop_device keyboard`

```
Traceback (most recent call last):
  File "/home/yanxi/orbit-surgical/source/standalone/environments/teleoperation/teleop_se3_agent.py", line 149, in <module>
    main()
  File "/home/yanxi/orbit-surgical/source/standalone/environments/teleoperation/teleop_se3_agent.py", line 141, in main
    env.step(actions)
  File "/home/yanxi/miniconda3/envs/isaaclab/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
  File "/home/yanxi/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 156, in step
    self.action_manager.process_action(action.to(self.device))
  File "/home/yanxi/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/action_manager.py", line 300, in process_action
    raise ValueError(f"Invalid action shape, expected: {self.total_action_dim}, received: {action.shape[1]}.")
ValueError: Invalid action shape, expected: 4, received: 7.
```

I followed the instructions to set up the environment and the Basic agents work fine.

**Comment by masoudmoghani** [comment]
Hi @relifeto18 I fixed the command_type for the Lift-Needle task and the teleop script should run fine. Thanks.
